apiVersion: v1
kind: Pod
metadata:
  name: debug

spec:
  containers:
  - name: debug
    image: alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - "sleep"
    - "10000"